{
  "uid" : "46d01cf4fc756a43",
  "name" : "Тест логина для юзера apexknight@yandex.ru в окружении dev",
  "fullName" : "tests.ui.auth.test_login#test_login_ui_dev",
  "historyId" : "2d5f7d1436342838c5d72ec97bea311a",
  "time" : {
    "start" : 1732617175042,
    "stop" : 1732617193946,
    "duration" : 18904
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Таймаут ожидания URL: /main",
  "statusTrace" : "self = <base.pages.login_page.LoginPage object at 0x7fe357c43f70>\nexpected_url_fragment = '/main', timeout = 15\n\n    def verify_redirect(self, expected_url_fragment, timeout=15):\n        try:\n>           WebDriverWait(self.driver, timeout).until(EC.url_contains(expected_url_fragment))\n\nbase/base_page.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"5a5a7343-ef12-4a72-a3ec-0bd268f53919\")>\nmethod = <function url_contains.<locals>._predicate at 0x7fe35735be20>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nsetup_driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"5a5a7343-ef12-4a72-a3ec-0bd268f53919\")>\n\n    @pytest.mark.dev\n    @allure.story(\"Логин\")\n    @allure.title(f\"Тест логина для юзера {MAIL} в окружении dev\")\n    def test_login_ui_dev(setup_driver):\n        landing = os.getenv('LANDING_DEV')\n        driver = setup_driver\n        driver.get(landing)\n    \n        login_page = LoginPage(driver)\n    \n        with allure.step(\"Нажимаем кнопку 'Начать'\"):\n            login_page.get_started()\n    \n        with allure.step(\"Вводим почту\"):\n            print(f'ETA POCHTA {MAIL}')\n            login_page.enter_email(MAIL)\n    \n        with allure.step(\"Вводим пароль\"):\n            login_page.enter_password(PASSW)\n    \n        with allure.step(\"Нажимаем кнопку вход\"):\n            login_page.submit()\n    \n>       login_page.verify_redirect(\"/main\")\n\ntests/ui/auth/test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <base.pages.login_page.LoginPage object at 0x7fe357c43f70>\nexpected_url_fragment = '/main', timeout = 15\n\n    def verify_redirect(self, expected_url_fragment, timeout=15):\n        try:\n            WebDriverWait(self.driver, timeout).until(EC.url_contains(expected_url_fragment))\n            current_url = self.driver.current_url\n            assert expected_url_fragment in current_url, (\n                f\"Тест не пройден: не попали на {expected_url_fragment}, текущий URL: {current_url}\"\n            )\n        except TimeoutException:\n            self.take_screenshot(\"screenshot_error\")\n>           raise AssertionError(f\"Таймаут ожидания URL: {expected_url_fragment}\")\nE           AssertionError: Таймаут ожидания URL: /main\n\nbase/base_page.py:30: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "setup_driver",
    "time" : {
      "start" : 1732617161743,
      "stop" : 1732617175041,
      "duration" : 13298
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: Таймаут ожидания URL: /main",
    "statusTrace" : "self = <base.pages.login_page.LoginPage object at 0x7fe357c43f70>\nexpected_url_fragment = '/main', timeout = 15\n\n    def verify_redirect(self, expected_url_fragment, timeout=15):\n        try:\n>           WebDriverWait(self.driver, timeout).until(EC.url_contains(expected_url_fragment))\n\nbase/base_page.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"5a5a7343-ef12-4a72-a3ec-0bd268f53919\")>\nmethod = <function url_contains.<locals>._predicate at 0x7fe35735be20>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nsetup_driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"5a5a7343-ef12-4a72-a3ec-0bd268f53919\")>\n\n    @pytest.mark.dev\n    @allure.story(\"Логин\")\n    @allure.title(f\"Тест логина для юзера {MAIL} в окружении dev\")\n    def test_login_ui_dev(setup_driver):\n        landing = os.getenv('LANDING_DEV')\n        driver = setup_driver\n        driver.get(landing)\n    \n        login_page = LoginPage(driver)\n    \n        with allure.step(\"Нажимаем кнопку 'Начать'\"):\n            login_page.get_started()\n    \n        with allure.step(\"Вводим почту\"):\n            print(f'ETA POCHTA {MAIL}')\n            login_page.enter_email(MAIL)\n    \n        with allure.step(\"Вводим пароль\"):\n            login_page.enter_password(PASSW)\n    \n        with allure.step(\"Нажимаем кнопку вход\"):\n            login_page.submit()\n    \n>       login_page.verify_redirect(\"/main\")\n\ntests/ui/auth/test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <base.pages.login_page.LoginPage object at 0x7fe357c43f70>\nexpected_url_fragment = '/main', timeout = 15\n\n    def verify_redirect(self, expected_url_fragment, timeout=15):\n        try:\n            WebDriverWait(self.driver, timeout).until(EC.url_contains(expected_url_fragment))\n            current_url = self.driver.current_url\n            assert expected_url_fragment in current_url, (\n                f\"Тест не пройден: не попали на {expected_url_fragment}, текущий URL: {current_url}\"\n            )\n        except TimeoutException:\n            self.take_screenshot(\"screenshot_error\")\n>           raise AssertionError(f\"Таймаут ожидания URL: {expected_url_fragment}\")\nE           AssertionError: Таймаут ожидания URL: /main\n\nbase/base_page.py:30: AssertionError",
    "steps" : [ {
      "name" : "Нажимаем кнопку 'Начать'",
      "time" : {
        "start" : 1732617176654,
        "stop" : 1732617178678,
        "duration" : 2024
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Вводим почту",
      "time" : {
        "start" : 1732617178678,
        "stop" : 1732617178743,
        "duration" : 65
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Вводим пароль",
      "time" : {
        "start" : 1732617178743,
        "stop" : 1732617178772,
        "duration" : 29
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Нажимаем кнопку вход",
      "time" : {
        "start" : 1732617178772,
        "stop" : 1732617178795,
        "duration" : 23
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "setup_driver::0",
    "time" : {
      "start" : 1732617193989,
      "stop" : 1732617194739,
      "duration" : 750
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "Логин"
  }, {
    "name" : "tag",
    "value" : "dev"
  }, {
    "name" : "parentSuite",
    "value" : "tests.ui.auth"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "host",
    "value" : "fv-az1652-217"
  }, {
    "name" : "thread",
    "value" : "2178-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.ui.auth.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "dev" ]
  },
  "source" : "46d01cf4fc756a43.json",
  "parameterValues" : [ ]
}